# Generated by Django 5.2.4 on 2025-07-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando_region', models.CharField(max_length=100, verbose_name='Comando / Región')),
                ('titulo_abreviado', models.CharField(max_length=50, verbose_name='Título Abreviado')),
                ('detalle_unidad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Detalle de la Unidad')),
                ('modelo_equipo_fortinet', models.CharField(max_length=100, verbose_name='Modelo Equipo (Fortinet)')),
                ('serie_fortinet', models.CharField(max_length=100, unique=True, verbose_name='Serie (Fortinet)')),
                ('oblea_fortinet', models.CharField(blank=True, max_length=50, null=True, verbose_name='Oblea (Fortinet)')),
                ('ospf', models.CharField(blank=True, max_length=20, null=True, verbose_name='OSPF')),
                ('ip_admin', models.CharField(max_length=15, unique=True, verbose_name='IP Admin')),
                ('direccion_subred', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección Subred')),
                ('red_dmz', models.CharField(blank=True, max_length=50, null=True, verbose_name='Red DMZ')),
                ('red_wifi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Red WiFi')),
                ('modelo_equipo_switch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo Equipo (Switch Fortinet)')),
                ('serie_switch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serie (Switch Fortinet)')),
                ('oblea_switch', models.CharField(blank=True, max_length=50, null=True, verbose_name='Oblea (Switch Fortinet)')),
                ('grupo_admin_ldap', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo Admin LDAP')),
                ('apellido_nombre_admin', models.CharField(max_length=100, verbose_name='Apellido y Nombre (Admin Unidad)')),
                ('telefono_admin', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono (Admin Unidad)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activo de Red',
                'verbose_name_plural': 'Activos de Red',
                'ordering': ['comando_region', 'ip_admin'],
            },
        ),
    ]
