# Generated by Django 4.2.4 on 2025-07-12 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='modelo_equipo_switch',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='oblea_switch',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='serie_switch',
        ),
        migrations.CreateModel(
            name='FortiSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_equipo', models.CharField(max_length=100, verbose_name='Modelo Equipo (Switch Fortinet)')),
                ('serie', models.CharField(max_length=100, verbose_name='Serie (Switch Fortinet)')),
                ('oblea', models.CharField(blank=True, max_length=50, null=True, verbose_name='Oblea (Switch Fortinet)')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='core.activo')),
            ],
        ),
    ]
