# Generated by Django 4.2.4 on 2025-07-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_activo_modelo_equipo_switch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('observacion', 'En observación'), ('quemado', 'Quemado'), ('baja', 'Dado de baja')], default='activo', max_length=20, verbose_name='Estado del Activo'),
        ),
    ]
