# Generated by Django 5.2.4 on 2025-07-13 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activo_estado'),
        ('core', '0004_estadohistorico'),
    ]

    operations = [
    ]
