# Generated by Django 5.2.4 on 2025-08-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_0003_activo_estado_0004_estadohistorico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='comando_region',
            field=models.CharField(max_length=100, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='fortiswitch',
            name='modelo_equipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fortiswitch',
            name='oblea',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fortiswitch',
            name='serie',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
