# Generated by Django 5.2.4 on 2025-08-13 02:28

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_activo_comando_region_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fortiswitch',
            options={'ordering': ['activo_id', 'modelo_equipo', 'serie']},
        ),
        migrations.AlterField(
            model_name='activo',
            name='comando_region',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('observacion', 'En observación'), ('quemado', 'Quemado'), ('baja', 'Dado de baja')], db_index=True, default='activo', max_length=20, verbose_name='Estado del Activo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='ip_admin',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='IP Admin'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='modelo_equipo_fortinet',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Modelo Equipo (Fortinet)'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='telefono_admin',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[\\d\\-\\+\\s\\(\\)]+$')], verbose_name='Teléfono (Admin Unidad)'),
        ),
        migrations.AlterField(
            model_name='fortiswitch',
            name='modelo_equipo',
            field=models.CharField(choices=[('FortiSwitch 224E', 'FortiSwitch 224E'), ('FortiSwitch 248E', 'FortiSwitch 248E')], db_index=True, max_length=100, verbose_name='Modelo del Switch'),
        ),
        migrations.AlterField(
            model_name='fortiswitch',
            name='oblea',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Oblea (Switch)'),
        ),
        migrations.AlterField(
            model_name='fortiswitch',
            name='serie',
            field=models.CharField(max_length=100, verbose_name='Serie (Switch)'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['comando_region'], name='core_activo_comando_dbd78e_idx'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['estado'], name='core_activo_estado_49efd9_idx'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['modelo_equipo_fortinet'], name='core_activo_modelo__eb829f_idx'),
        ),
        migrations.AddIndex(
            model_name='fortiswitch',
            index=models.Index(fields=['modelo_equipo'], name='core_fortis_modelo__2cc4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='fortiswitch',
            index=models.Index(fields=['serie'], name='core_fortis_serie_89e7e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='activo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('oblea_fortinet'), condition=models.Q(('oblea_fortinet__isnull', False)), name='uq_activo_oblea_ci'),
        ),
        migrations.AddConstraint(
            model_name='fortiswitch',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('serie'), name='uq_switch_serie_ci'),
        ),
        migrations.AddConstraint(
            model_name='fortiswitch',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('oblea'), condition=models.Q(('oblea__isnull', False)), name='uq_switch_oblea_ci'),
        ),
    ]
