# Generated by Django 5.2.4 on 2025-08-14 12:48

from django.db import migrations

def enable_citext(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("CREATE EXTENSION IF NOT EXISTS citext;")

def disable_citext(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("DROP EXTENSION IF EXISTS citext;")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_fortiswitch_options_and_more'),
    ]

    operations = [
        migrations.RunPython(enable_citext, disable_citext),
    ]
