# Generated by Django 5.2.4 on 2025-08-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_enable_citext'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activo',
            name='uq_activo_oblea_ci',
        ),
        migrations.RemoveConstraint(
            model_name='fortiswitch',
            name='uq_switch_serie_ci',
        ),
        migrations.RemoveConstraint(
            model_name='fortiswitch',
            name='uq_switch_oblea_ci',
        ),
        migrations.RemoveIndex(
            model_name='fortiswitch',
            name='core_fortis_serie_89e7e0_idx',
        ),
        migrations.AlterField(
            model_name='activo',
            name='oblea_fortinet',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Oblea (Fortinet)'),
        ),
        migrations.AlterField(
            model_name='fortiswitch',
            name='oblea',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Oblea (Switch)'),
        ),
        migrations.AlterField(
            model_name='fortiswitch',
            name='serie',
            field=models.CharField(max_length=100, unique=True, verbose_name='Serie (Switch)'),
        ),
    ]
